[package]
name = "graph_practice"
version = "0.1.0"
authors = ["K Suzu <e40keisuke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue='0.6.0'